### ISSUE TITLE
.nd2 file vs TIFF file

### ISSUE THREAD

**Issue by sethb3744** [linnarsson-lab/pysmFISH#3]
Hi,

As per my first issue reported, I am still unable to install the pysmFISH pipeline. However, I have been reading through the documentation, and I am curious to know if .tif files can be used with the program at all in place of an .nd2 file. And if not, would you happen to know how .tif files could possibly be converted to .nd2 files. I realize that the answer to both of these is most likely no, but I wanted to ask just in case. 

Thanks,
Seth

**Comment by simone-codeluppi** [comment]
In order to run the analysis on .tiff files you need to replace the nikon .nd2 parser with one for tiff (as you suggested in the email). Which type of tiff you have ome-tiff or general tiff? Another important thing is that if you experiment in not large and you don’t need to run the stitching ,you should first test the process_standalone_experiment script.(http://linnarssonlab.org/pysmFISH/pipeline/scripts/process_standalone_experiment_ref.html). It doesn’t require yaml files with the settings needed for processing because you are able to enter the processing parameters directly into the script call. However you will need to modify the “ # Convert the .nd2 data” part of the source code in this script as well. If you want I can highlight which part needs to be modified and/or helping you in writing a parser (for .tiff is probably one single line using skimge.io) and create a version of the process_standalone_experiment script that uses tiff or directly numpy arrays.
